name: GlobalMarket
main: com.upgrade.globalmarket.internal.plugin.GlobalMarket
authors:
  - Blank038
  - chenasyd
depend:
  - AyCore
  - NBTAPI
softdepend:
  - Vault
  - PlayerPoints
  - NyEconomy
version: 2.7.3
api-version: 1.13
commands:
  globalmarket:
    aliases:
      - market
      - sale
    description: Command for GlobalMarket.
folia-supported: true